apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordpress-canary-deployment
  namespace: exercise-03
  labels:
    app: wordpress
    track: canary
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: bitnami/wordpress:4.9.5
      name: wordpress
      env:
          - name: MARIADB_DATABASE
            valueFrom:
              configMapKeyRef:
                name: wordpress-mariadb-config-map
                key: mariadb_database
          - name: WORDPRESS_USERNAME
            valueFrom:
              secretKeyRef:
                name: wordpress-secrets
                key: wp_username
          - name: WORDPRESS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: wordpress-secrets
                key: wp_password
          - name: WORDPRESS_BLOG_NAME
            valueFrom:
              secretKeyRef:
                name: wordpress-secrets
                key: wp_blog_name
          - name: WORDPRESS_FIRST_NAME
            valueFrom:
              secretKeyRef:
                name: wordpress-secrets
                key: wp_first_name
          - name: WORDPRESS_LAST_NAME
            valueFrom:
              secretKeyRef:
                name: wordpress-secrets
                key: wp_last_name
          - name: WORDPRESS_LAST_NAME
            valueFrom:
              secretKeyRef:
                name: wordpress-secrets
                key: wp_last_name
          - name: WORDPRESS_HOSTNAME
            valueFrom:
              secretKeyRef:
                name: wordpress-secrets
                key: wp_hostname
          - name: DATABASE_NAME
            valueFrom:
              secretKeyRef:
                name: wordpress-secrets
                key: database_name
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: wordpress-secrets
                key: database_user
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: wordpress-secrets
                key: database_password
      ports:
        - containerPort: 80
          name: wordpress
      readinessProbe:
          httpGet:
          path: /wp-admin
          port: http
          initialDelaySeconds: 15
      livenessProbe:
          httpGet:
          path: /wp-admin
          port: http
          initialDelaySeconds: 15
          periodSeconds: 5
