# Exercise 3 of session 1: Mariadb deployment
# Pedro Ignacio Respaldiza Hidalgo (aka Iñaki Respaldiza)
# K8s Training user: pedro_respaldiza
---
apiVersion: v1
data:
  dbname: azhzX3RyYWluaW5nX2RiXzA3
  dbpassword: Yml0bmFtaS10cmFpbmluZy0yMDE4
  dbuser: azhzX3RyYWluaW5nX3VzZXJfMDc=
kind: Secret
metadata:
  creationTimestamp: null
  name: mariadb-secret
  namespace: exercise-03
