{{- if .Values.persistence.enabled -}}
    kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.persistence.storage_class }}
provisioner: kubernetes.io/vsphere-volume
parameters:
    diskformat: thin

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ .Values.persistence.name_volumen }}
  labels:
    type: {{ .Values.persistence.storage_class }}
spec:
  storageClassName: {{ .Values.persistence.storage_class }}
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.persistence.path_local | quote }}
{{- end }}