 kind: ClusterRole
 apiVersion: rbac.authorization.k8s.io/v1beta1
 metadata:
    name: dev-role
 rules:
  - apiGroups: ["*"] 
    resources: [""]
    verbs: ["get", "list","watchs"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dev-role-binding
subjects:
- kind: User
  name: jsalmeron 
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: juan 
  apiGroup: rbac.authorization.k8s.io  
roleRef:
  kind: ClusterRole
  name: all-pod-access
  apiGroup: rbac.authorization.k8s.io

