 kind: ClusterRole
 apiVersion: rbac.authorization.k8s.io/v1beta1
 metadata:
    name: sres-role
 rules:
  - apiGroups: ["*"] 
    resources: ["secrets"]
    verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sres-role-binding
subjects:
- kind: User
  name: dbarranco 
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: sres -role
  apiGroup: rbac.authorization.k8s.io

