apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: exercise-01
  annotations:
    nginx.ingress.kubernetes.io/affinity: cookie
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
  type: LoadBalancer